version: v1
debug: true
bot:
  prefix: /sealos_bot
  allowOps:
    - sealos-ci-robot
    - sealos-release-robot
  email: sealos-ci-robot@sealos.io
  username: sealos-ci-robot
  changelog: scripts/changelog.sh
repo:
  org: true
  name: labring-actions/sealos
  fork: cuisongliu/sealos

changelog:
  allowOps:
    - cuisongliu
  reviewers:
    - cuisongliu

release:
  allowOps:
    - cuisongliu

message:
  success: |
    🤖 says: this action finished successfully 🎉
  format_error: |
    🤖 says: ‼️ this action format error, please check the format of this action.
  permission_error: |
    🤖 says: ‼️ no has permission to trigger this action.
