name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.20.x
      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo tag_name=${TAG} >> $GITHUB_OUTPUT
      - uses: sigstore/cosign-installer@v3.0.1
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.G_REGISTRY_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release  --timeout=1h --debug
        env:
          GITHUB_TOKEN: ${{ secrets.G_REGISTRY_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          USERNAME: ${{ github.repository_owner }}
